#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-IO-Socket-Socks
Version  : 0.74
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/O/OL/OLEG/IO-Socket-Socks-0.74.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/O/OL/OLEG/IO-Socket-Socks-0.74.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libi/libio-socket-socks-perl/libio-socket-socks-perl_0.74-1.debian.tar.xz
Summary  : 'Provides a way to create socks client or server both 4 and 5 version.'
Group    : Development/Tools
License  : LGPL-2.1
Requires: perl-IO-Socket-Socks-license
Requires: perl-IO-Socket-Socks-man

%description
This module seeks to provide a full implementation of the SOCKS protocol
while behaving like a regular socket as much as possible.

%package license
Summary: license components for the perl-IO-Socket-Socks package.
Group: Default

%description license
license components for the perl-IO-Socket-Socks package.


%package man
Summary: man components for the perl-IO-Socket-Socks package.
Group: Default

%description man
man components for the perl-IO-Socket-Socks package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n IO-Socket-Socks-0.74
mkdir -p %{_topdir}/BUILD/IO-Socket-Socks-0.74/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/IO-Socket-Socks-0.74/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-IO-Socket-Socks
cp deblicense/copyright %{buildroot}/usr/share/doc/perl-IO-Socket-Socks/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/IO/Socket/Socks.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-IO-Socket-Socks/deblicense_copyright

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/IO::Socket::Socks.3
